services:
  - type: web
    name: tgqwen
    env: python
    region: frankfurt
    buildCommand: pip install -r requirements.txt && python database/init_db.py
    startCommand: python server.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        value: 10000